### ISSUE TITLE
Do suitable 'Minimal Metadata About ...' (MIA...) standards exist for your experiments?

### ISSUE THREAD

**Issue by DSWGlobal** [DSWGlobal/dsw#11]
The FAIRsharing website is not very user friendly and while I often point researchers to this website, most of them don't understand it and don't know what to do with the info on the website. To be honest, while i understand the principle and thye intended goal, I also don't understand what funders actually want and expect from researchers with respect to metadata schemas. Just dumping this website on researchers and support staff will achieve very little.  Out of 100+ DMPs that I have seen I have only once seen that a reasearcher refers to a discipline-related metadataschema; in most cases collecting your "own" metadata makes a lot more sense. 
Some guidelines, expected outcomes or examples on this topic would be much more useful then referring to websites with metadataschemas.

**Comment by KarelBerka** [comment]
This pointing to farsharing.org is however first example of suggestions that should be available for other questions as well.

**Comment by rwwh** [comment]
Since this issue was raised we have implemented an integration with FAIRSharing. I just added another question (to be released after Biohackathon) where people can list the Minimal information standards using the FAIRSharing API. 

It may be needed to make further clarifications in our guidance text, but I think this improves things a lot already.
