### ISSUE TITLE
Why only Dublin Core here?

### ISSUE THREAD

**Issue by DSWGlobal** [DSWGlobal/dsw#65]
There are better, more comprehensive metadata standards like DDI or DataCite for this.

**Comment by rwwh** [comment]
The reason was that Funder templates are asking whether DC is used. But this is a good issue, and I have added DataCite and DDI questions, it should become available in core KM version 2.3.0

@MarekSuchanek Can we add the 035a37e5-1dda-44a1-8b66-d0612e99cd14 and 9320bf04-824b-46b3-ae8b-55240e2d04b9 to the Science Europe template next to 8d3b85e0-1683-48a5-a650-9f0d9bf8a1a4 ?

**Comment by MarekSuchanek** [comment]
OK, included questions about DataCite and DDI in the Science Europe template, will be released as 1.3.0.
